/**
 * ROLE-BASED ACCESS CONTROL (RBAC) SYSTEM
 * Complete permission management for MindStack
 * 
 * Features:
 * - Multiple user roles with granular permissions
 * - Offline-first architecture
 * - Permission caching
 * - Audit logging
 */

/**
 * USER ROLES
 */
export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',       // Full system access
  ADMIN: 'ADMIN',                   // Organization admin
  ACCOUNTANT: 'ACCOUNTANT',         // Full accounting access
  MANAGER: 'MANAGER',               // View and approve
  CASHIER: 'CASHIER',               // Cash transactions only
  SALES_PERSON: 'SALES_PERSON',     // Sales and invoicing
  INVENTORY_MANAGER: 'INVENTORY_MANAGER', // Inventory management
  AUDITOR: 'AUDITOR',               // Read-only access
  DATA_ENTRY: 'DATA_ENTRY',         // Basic data entry
  VIEWER: 'VIEWER'                  // View-only access
};

/**
 * PERMISSION MODULES
 */
export const MODULES = {
  // Core Accounting
  JOURNAL: 'JOURNAL',
  LEDGER: 'LEDGER',
  TRIAL_BALANCE: 'TRIAL_BALANCE',
  PROFIT_LOSS: 'PROFIT_LOSS',
  BALANCE_SHEET: 'BALANCE_SHEET',
  CASH_FLOW: 'CASH_FLOW',
  
  // Transactions
  PAYMENT: 'PAYMENT',
  RECEIPT: 'RECEIPT',
  CONTRA: 'CONTRA',
  SALES: 'SALES',
  PURCHASE: 'PURCHASE',
  DEBIT_NOTE: 'DEBIT_NOTE',
  CREDIT_NOTE: 'CREDIT_NOTE',
  
  // GST
  GST_INVOICE: 'GST_INVOICE',
  GST_REPORTS: 'GST_REPORTS',
  GSTR1: 'GSTR1',
  GSTR3B: 'GSTR3B',
  E_INVOICE: 'E_INVOICE',
  E_WAY_BILL: 'E_WAY_BILL',
  
  // TDS
  TDS_DEDUCTION: 'TDS_DEDUCTION',
  TDS_PAYMENT: 'TDS_PAYMENT',
  TDS_RETURNS: 'TDS_RETURNS',
  FORM_26AS: 'FORM_26AS',
  
  // Inventory
  INVENTORY: 'INVENTORY',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
  STOCK_TRANSFER: 'STOCK_TRANSFER',
  STOCK_REPORT: 'STOCK_REPORT',
  
  // Banking
  BANK_ACCOUNT: 'BANK_ACCOUNT',
  BANK_RECONCILIATION: 'BANK_RECONCILIATION',
  BANK_STATEMENT: 'BANK_STATEMENT',
  
  // Masters
  ACCOUNT_MASTER: 'ACCOUNT_MASTER',
  PARTY_MASTER: 'PARTY_MASTER',
  ITEM_MASTER: 'ITEM_MASTER',
  BANK_MASTER: 'BANK_MASTER',
  
  // Settings
  COMPANY_SETTINGS: 'COMPANY_SETTINGS',
  USER_MANAGEMENT: 'USER_MANAGEMENT',
  ROLE_MANAGEMENT: 'ROLE_MANAGEMENT',
  BACKUP_RESTORE: 'BACKUP_RESTORE',
  DATA_EXPORT: 'DATA_EXPORT',
  DATA_IMPORT: 'DATA_IMPORT',
  
  // Reports
  FINANCIAL_REPORTS: 'FINANCIAL_REPORTS',
  TAX_REPORTS: 'TAX_REPORTS',
  INVENTORY_REPORTS: 'INVENTORY_REPORTS',
  CUSTOM_REPORTS: 'CUSTOM_REPORTS',
  
  // Audit
  AUDIT_LOG: 'AUDIT_LOG',
  ACTIVITY_LOG: 'ACTIVITY_LOG',
  
  // Advanced
  YEAR_END_CLOSING: 'YEAR_END_CLOSING',
  DATA_MIGRATION: 'DATA_MIGRATION',
  SYSTEM_SETTINGS: 'SYSTEM_SETTINGS'
};

/**
 * PERMISSION ACTIONS
 */
export const ACTIONS = {
  CREATE: 'CREATE',
  READ: 'READ',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  VOID: 'VOID',
  EXPORT: 'EXPORT',
  IMPORT: 'IMPORT',
  PRINT: 'PRINT'
};

/**
 * ROLE PERMISSIONS MATRIX
 * Defines what each role can do
 */
export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: {
    // Full access to everything
    '*': [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, 
          ACTIONS.APPROVE, ACTIONS.REJECT, ACTIONS.VOID, ACTIONS.EXPORT, 
          ACTIONS.IMPORT, ACTIONS.PRINT]
  },
  
  [ROLES.ADMIN]: {
    // All modules except system settings
    [MODULES.JOURNAL]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.VOID],
    [MODULES.LEDGER]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.TRIAL_BALANCE]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PROFIT_LOSS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.BALANCE_SHEET]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.CASH_FLOW]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    
    [MODULES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE],
    [MODULES.RECEIPT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE],
    [MODULES.CONTRA]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE],
    [MODULES.PURCHASE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.APPROVE],
    [MODULES.DEBIT_NOTE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.CREDIT_NOTE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    
    [MODULES.GST_INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE, ACTIONS.PRINT],
    [MODULES.GST_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.GSTR1]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.GSTR3B]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.E_INVOICE]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.E_WAY_BILL]: [ACTIONS.CREATE, ACTIONS.READ],
    
    [MODULES.TDS_DEDUCTION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.TDS_PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.TDS_RETURNS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.FORM_26AS]: [ACTIONS.READ, ACTIONS.EXPORT],
    
    [MODULES.INVENTORY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.STOCK_ADJUSTMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.APPROVE],
    [MODULES.STOCK_TRANSFER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.APPROVE],
    [MODULES.STOCK_REPORT]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    
    [MODULES.BANK_ACCOUNT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.BANK_RECONCILIATION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.BANK_STATEMENT]: [ACTIONS.READ, ACTIONS.IMPORT],
    
    [MODULES.ACCOUNT_MASTER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.PARTY_MASTER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.ITEM_MASTER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.BANK_MASTER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    
    [MODULES.COMPANY_SETTINGS]: [ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.USER_MANAGEMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.ROLE_MANAGEMENT]: [ACTIONS.READ],
    [MODULES.BACKUP_RESTORE]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.DATA_EXPORT]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.DATA_IMPORT]: [ACTIONS.CREATE, ACTIONS.READ],
    
    [MODULES.FINANCIAL_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.TAX_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.INVENTORY_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.CUSTOM_REPORTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    
    [MODULES.AUDIT_LOG]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.ACTIVITY_LOG]: [ACTIONS.READ, ACTIONS.EXPORT],
    
    [MODULES.YEAR_END_CLOSING]: [ACTIONS.CREATE, ACTIONS.READ]
  },
  
  [ROLES.ACCOUNTANT]: {
    // Full accounting access, limited admin
    [MODULES.JOURNAL]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.LEDGER]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.TRIAL_BALANCE]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PROFIT_LOSS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.BALANCE_SHEET]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.CASH_FLOW]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    
    [MODULES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.RECEIPT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.CONTRA]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.PURCHASE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.DEBIT_NOTE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.CREDIT_NOTE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    
    [MODULES.GST_INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.PRINT],
    [MODULES.GST_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.GSTR1]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.GSTR3B]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.E_INVOICE]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.E_WAY_BILL]: [ACTIONS.CREATE, ACTIONS.READ],
    
    [MODULES.TDS_DEDUCTION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.TDS_PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.TDS_RETURNS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.FORM_26AS]: [ACTIONS.READ, ACTIONS.EXPORT],
    
    [MODULES.BANK_RECONCILIATION]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.BANK_STATEMENT]: [ACTIONS.READ, ACTIONS.IMPORT],
    
    [MODULES.ACCOUNT_MASTER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.PARTY_MASTER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    
    [MODULES.FINANCIAL_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.TAX_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    
    [MODULES.AUDIT_LOG]: [ACTIONS.READ]
  },
  
  [ROLES.MANAGER]: {
    // View and approve access
    [MODULES.JOURNAL]: [ACTIONS.READ],
    [MODULES.LEDGER]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.TRIAL_BALANCE]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PROFIT_LOSS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.BALANCE_SHEET]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    
    [MODULES.PAYMENT]: [ACTIONS.READ, ACTIONS.APPROVE, ACTIONS.REJECT],
    [MODULES.RECEIPT]: [ACTIONS.READ, ACTIONS.APPROVE, ACTIONS.REJECT],
    [MODULES.SALES]: [ACTIONS.READ, ACTIONS.APPROVE],
    [MODULES.PURCHASE]: [ACTIONS.READ, ACTIONS.APPROVE],
    
    [MODULES.GST_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.INVENTORY]: [ACTIONS.READ],
    [MODULES.STOCK_ADJUSTMENT]: [ACTIONS.READ, ACTIONS.APPROVE],
    [MODULES.STOCK_REPORT]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    
    [MODULES.FINANCIAL_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.TAX_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.INVENTORY_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT]
  },
  
  [ROLES.CASHIER]: {
    // Cash transactions only
    [MODULES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.RECEIPT]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.CONTRA]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.PRINT],
    
    [MODULES.GST_INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.PRINT],
    [MODULES.PARTY_MASTER]: [ACTIONS.READ]
  },
  
  [ROLES.SALES_PERSON]: {
    // Sales and invoicing
    [MODULES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.PRINT],
    [MODULES.RECEIPT]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.CREDIT_NOTE]: [ACTIONS.CREATE, ACTIONS.READ],
    
    [MODULES.GST_INVOICE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.PRINT],
    [MODULES.E_WAY_BILL]: [ACTIONS.CREATE, ACTIONS.READ],
    
    [MODULES.PARTY_MASTER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.ITEM_MASTER]: [ACTIONS.READ],
    [MODULES.INVENTORY]: [ACTIONS.READ]
  },
  
  [ROLES.INVENTORY_MANAGER]: {
    // Inventory management
    [MODULES.INVENTORY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.STOCK_ADJUSTMENT]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.STOCK_TRANSFER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.STOCK_REPORT]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    
    [MODULES.PURCHASE]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [MODULES.DEBIT_NOTE]: [ACTIONS.CREATE, ACTIONS.READ],
    
    [MODULES.ITEM_MASTER]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [MODULES.PARTY_MASTER]: [ACTIONS.READ],
    
    [MODULES.INVENTORY_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT]
  },
  
  [ROLES.AUDITOR]: {
    // Read-only access to everything
    [MODULES.JOURNAL]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.LEDGER]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.TRIAL_BALANCE]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.PROFIT_LOSS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.BALANCE_SHEET]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.CASH_FLOW]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    
    [MODULES.PAYMENT]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.RECEIPT]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.SALES]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.PURCHASE]: [ACTIONS.READ, ACTIONS.EXPORT],
    
    [MODULES.GST_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.TDS_RETURNS]: [ACTIONS.READ, ACTIONS.EXPORT],
    
    [MODULES.INVENTORY]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.BANK_RECONCILIATION]: [ACTIONS.READ, ACTIONS.EXPORT],
    
    [MODULES.FINANCIAL_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.TAX_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    [MODULES.INVENTORY_REPORTS]: [ACTIONS.READ, ACTIONS.EXPORT, ACTIONS.PRINT],
    
    [MODULES.AUDIT_LOG]: [ACTIONS.READ, ACTIONS.EXPORT],
    [MODULES.ACTIVITY_LOG]: [ACTIONS.READ, ACTIONS.EXPORT]
  },
  
  [ROLES.DATA_ENTRY]: {
    // Basic data entry
    [MODULES.PAYMENT]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.RECEIPT]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.SALES]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.PURCHASE]: [ACTIONS.CREATE, ACTIONS.READ],
    
    [MODULES.PARTY_MASTER]: [ACTIONS.CREATE, ACTIONS.READ],
    [MODULES.ITEM_MASTER]: [ACTIONS.READ]
  },
  
  [ROLES.VIEWER]: {
    // View-only access
    [MODULES.LEDGER]: [ACTIONS.READ],
    [MODULES.TRIAL_BALANCE]: [ACTIONS.READ],
    [MODULES.PROFIT_LOSS]: [ACTIONS.READ],
    [MODULES.BALANCE_SHEET]: [ACTIONS.READ],
    
    [MODULES.PAYMENT]: [ACTIONS.READ],
    [MODULES.RECEIPT]: [ACTIONS.READ],
    [MODULES.SALES]: [ACTIONS.READ],
    [MODULES.PURCHASE]: [ACTIONS.READ],
    
    [MODULES.INVENTORY]: [ACTIONS.READ],
    [MODULES.FINANCIAL_REPORTS]: [ACTIONS.READ]
  }
};

/**
 * Permission Service Class
 */
class PermissionService {
  constructor() {
    this.currentUser = null;
    this.permissionCache = new Map();
  }

  /**
   * Set current user
   */
  setCurrentUser(user) {
    this.currentUser = user;
    this.permissionCache.clear();
  }

  /**
   * Check if user has permission
   */
  hasPermission(module, action) {
    if (!this.currentUser) {
      return false;
    }

    // Check cache first
    const cacheKey = `${module}:${action}`;
    if (this.permissionCache.has(cacheKey)) {
      return this.permissionCache.get(cacheKey);
    }

    const role = this.currentUser.role;
    const permissions = ROLE_PERMISSIONS[role];

    if (!permissions) {
      this.permissionCache.set(cacheKey, false);
      return false;
    }

    // Super admin has all permissions
    if (permissions['*']) {
      this.permissionCache.set(cacheKey, true);
      return true;
    }

    // Check specific module permission
    const modulePermissions = permissions[module];
    if (!modulePermissions) {
      this.permissionCache.set(cacheKey, false);
      return false;
    }

    const hasAccess = modulePermissions.includes(action);
    this.permissionCache.set(cacheKey, hasAccess);
    return hasAccess;
  }

  /**
   * Check multiple permissions (AND logic)
   */
  hasAllPermissions(checks) {
    return checks.every(({ module, action }) => 
      this.hasPermission(module, action)
    );
  }

  /**
   * Check multiple permissions (OR logic)
   */
  hasAnyPermission(checks) {
    return checks.some(({ module, action }) => 
      this.hasPermission(module, action)
    );
  }

  /**
   * Get all permissions for current user
   */
  getUserPermissions() {
    if (!this.currentUser) {
      return {};
    }

    const role = this.currentUser.role;
    return ROLE_PERMISSIONS[role] || {};
  }

  /**
   * Get allowed actions for a module
   */
  getAllowedActions(module) {
    if (!this.currentUser) {
      return [];
    }

    const role = this.currentUser.role;
    const permissions = ROLE_PERMISSIONS[role];

    if (!permissions) {
      return [];
    }

    // Super admin has all actions
    if (permissions['*']) {
      return Object.values(ACTIONS);
    }

    return permissions[module] || [];
  }

  /**
   * Check if user can access module
   */
  canAccessModule(module) {
    return this.getAllowedActions(module).length > 0;
  }

  /**
   * Get accessible modules for current user
   */
  getAccessibleModules() {
    if (!this.currentUser) {
      return [];
    }

    const role = this.currentUser.role;
    const permissions = ROLE_PERMISSIONS[role];

    if (!permissions) {
      return [];
    }

    // Super admin has all modules
    if (permissions['*']) {
      return Object.values(MODULES);
    }

    return Object.keys(permissions);
  }

  /**
   * Clear permission cache
   */
  clearCache() {
    this.permissionCache.clear();
  }
}

// Create singleton instance
const permissionService = new PermissionService();

export default permissionService;
export { PermissionService };
